/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package RandomItems;

import java.util.Random;
import java.util.Vector;

public class GetRandomNames {

    public Vector SomeNames = new Vector();
public Vector SomeJobs = new Vector();

    public String OneName() {
        String results = RandomNames(1).elementAt(0).toString();
        return results;
    }
    
    public String OneProfession(){
        String results = RandomProfession(1).elementAt(0).toString();
        return results;
        
    }
    
public Vector RandomProfession(int num_names) {
        Vector results = new Vector();
        LoadList();
        Random rn = new Random();

        for (int i = 0; i < num_names; i++) {
            boolean duplicate = true;
            String name = "";
            while (duplicate == true) {
                int randomnum = rn.nextInt(SomeJobs.size() - 1) + 1;
                name = SomeJobs.elementAt(randomnum).toString();
                duplicate = ListContains(name, results);
            }
            results.addElement(name);

        }

        return results;
    }
    
    
    public Vector RandomNames(int num_names) {
        Vector results = new Vector();
        LoadList();
        Random rn = new Random();

        for (int i = 0; i < num_names; i++) {
            boolean duplicate = true;
            String name = "";
            while (duplicate == true) {
                int randomnum = rn.nextInt(SomeNames.size() - 1) + 1;
                name = SomeNames.elementAt(randomnum).toString();
                duplicate = ListContains(name, results);
            }
            results.addElement(name);

        }

        return results;
    }

    public boolean ListContains(String name, Vector list) {
        boolean contains = false;

        for (int i = 0; i < list.size(); i++) {
            if (list.elementAt(i).toString().trim().equals(name.trim())) {
                contains = true;
            }
        }
        return contains;
    }

    public void LoadList() {


        SomeNames.addElement("Jacob");
        SomeNames.addElement("Ethan");
        SomeNames.addElement("Michael");
        SomeNames.addElement("Jayden");
        SomeNames.addElement("William");
        SomeNames.addElement("Alexander");
        SomeNames.addElement("Noah");
        SomeNames.addElement("Daniel");
        SomeNames.addElement("Aiden");
        SomeNames.addElement("Anthony");
        SomeNames.addElement("Joshua");
        SomeNames.addElement("Mason");
        SomeNames.addElement("Christopher");
        SomeNames.addElement("Andrew");
        SomeNames.addElement("David");
        SomeNames.addElement("Matthew");
        SomeNames.addElement("Logan");
        SomeNames.addElement("Elijah");
        SomeNames.addElement("James");
        SomeNames.addElement("Joseph");
        SomeNames.addElement("Gabriel");
        SomeNames.addElement("Benjamin");
        SomeNames.addElement("Ryan");
        SomeNames.addElement("Samuel");
        SomeNames.addElement("Jackson");
        SomeNames.addElement("John");
        SomeNames.addElement("Nathan");
        SomeNames.addElement("Jonathan");
        SomeNames.addElement("Christian");
        SomeNames.addElement("Liam");
        SomeNames.addElement("Dylan");
        SomeNames.addElement("Landon");
        SomeNames.addElement("Caleb");
        SomeNames.addElement("Tyler");
        SomeNames.addElement("Lucas");
        SomeNames.addElement("Evan");
        SomeNames.addElement("Gavin");
        SomeNames.addElement("Nicholas");
        SomeNames.addElement("Isaac");
        SomeNames.addElement("Brayden");
        SomeNames.addElement("Luke");
        SomeNames.addElement("Angel");
        SomeNames.addElement("Brandon");
        SomeNames.addElement("Jack");
        SomeNames.addElement("Isaiah");
        SomeNames.addElement("Jordan");
        SomeNames.addElement("Owen");
        SomeNames.addElement("Carter");
        SomeNames.addElement("Connor");
        SomeNames.addElement("Justin");
        SomeNames.addElement("Jose");
        SomeNames.addElement("Jeremiah");
        SomeNames.addElement("Julian");
        SomeNames.addElement("Robert");
        SomeNames.addElement("Aaron");
        SomeNames.addElement("Adrian");
        SomeNames.addElement("Wyatt");
        SomeNames.addElement("Kevin");
        SomeNames.addElement("Hunter");
        SomeNames.addElement("Cameron");
        SomeNames.addElement("Zachary");
        SomeNames.addElement("Thomas");
        SomeNames.addElement("Charles");
        SomeNames.addElement("Austin");
        SomeNames.addElement("Eli");
        SomeNames.addElement("Chase");
        SomeNames.addElement("Henry");
        SomeNames.addElement("Sebastian");
        SomeNames.addElement("Jason");
        SomeNames.addElement("Levi");
        SomeNames.addElement("Xavier");
        SomeNames.addElement("Ian");
        SomeNames.addElement("Colton");
        SomeNames.addElement("Dominic");
        SomeNames.addElement("Juan");
        SomeNames.addElement("Cooper");
        SomeNames.addElement("Josiah");
        SomeNames.addElement("Luis");
        SomeNames.addElement("Ayden");
        SomeNames.addElement("Carson");
        SomeNames.addElement("Adam");
        SomeNames.addElement("Nathaniel");
        SomeNames.addElement("Brody");
        SomeNames.addElement("Tristan");
        SomeNames.addElement("Diego");
        SomeNames.addElement("Parker");
        SomeNames.addElement("Blake");
        SomeNames.addElement("Oliver");
        SomeNames.addElement("Cole");
        SomeNames.addElement("Carlos");
        SomeNames.addElement("Jaden");
        SomeNames.addElement("Jesus");
        SomeNames.addElement("Alex");
        SomeNames.addElement("Aidan");
        SomeNames.addElement("Eric");
        SomeNames.addElement("Hayden");
        SomeNames.addElement("Bryan");
        SomeNames.addElement("Max");
        SomeNames.addElement("Jaxon");
        SomeNames.addElement("Brian");
        SomeNames.addElement("Isabella");
        SomeNames.addElement("Sophia");
        SomeNames.addElement("Emma");
        SomeNames.addElement("Olivia");
        SomeNames.addElement("Ava");
        SomeNames.addElement("Emily");
        SomeNames.addElement("Abigail");
        SomeNames.addElement("Madison");
        SomeNames.addElement("Chloe");
        SomeNames.addElement("Mia");
        SomeNames.addElement("Addison");
        SomeNames.addElement("Elizabeth");
        SomeNames.addElement("Ella");
        SomeNames.addElement("Natalie");
        SomeNames.addElement("Samantha");
        SomeNames.addElement("Alexis");
        SomeNames.addElement("Lily");
        SomeNames.addElement("Grace");
        SomeNames.addElement("Hailey");
        SomeNames.addElement("Alyssa");
        SomeNames.addElement("Lillian");
        SomeNames.addElement("Hannah");
        SomeNames.addElement("Avery");
        SomeNames.addElement("Leah");
        SomeNames.addElement("Nevaeh");
        SomeNames.addElement("Sofia");
        SomeNames.addElement("Ashley");
        SomeNames.addElement("Anna");
        SomeNames.addElement("Brianna");
        SomeNames.addElement("Sarah");
        SomeNames.addElement("Zoe");
        SomeNames.addElement("Victoria");
        SomeNames.addElement("Gabriella");
        SomeNames.addElement("Brooklyn");
        SomeNames.addElement("Kaylee");
        SomeNames.addElement("Taylor");
        SomeNames.addElement("Layla");
        SomeNames.addElement("Allison");
        SomeNames.addElement("Evelyn");
        SomeNames.addElement("Riley");
        SomeNames.addElement("Amelia");
        SomeNames.addElement("Khloe");
        SomeNames.addElement("Makayla");
        SomeNames.addElement("Aubrey");
        SomeNames.addElement("Charlotte");
        SomeNames.addElement("Savannah");
        SomeNames.addElement("Zoey");
        SomeNames.addElement("Bella");
        SomeNames.addElement("Kayla");
        SomeNames.addElement("Alexa");
        SomeNames.addElement("Peyton");
        SomeNames.addElement("Audrey");
        SomeNames.addElement("Claire");
        SomeNames.addElement("Arianna");
        SomeNames.addElement("Julia");
        SomeNames.addElement("Aaliyah");
        SomeNames.addElement("Kylie");
        SomeNames.addElement("Lauren");
        SomeNames.addElement("Sophie");
        SomeNames.addElement("Sydney");
        SomeNames.addElement("Camila");
        SomeNames.addElement("Jasmine");
        SomeNames.addElement("Morgan");
        SomeNames.addElement("Alexandra");
        SomeNames.addElement("Jocelyn");
        SomeNames.addElement("Gianna");
        SomeNames.addElement("Maya");
        SomeNames.addElement("Kimberly");
        SomeNames.addElement("Mackenzie");
        SomeNames.addElement("Katherine");
        SomeNames.addElement("Destiny");
        SomeNames.addElement("Brooke");
        SomeNames.addElement("Trinity");
        SomeNames.addElement("Faith");
        SomeNames.addElement("Lucy");
        SomeNames.addElement("Madelyn");
        SomeNames.addElement("Madeline");
        SomeNames.addElement("Bailey");
        SomeNames.addElement("Payton");
        SomeNames.addElement("Andrea");
        SomeNames.addElement("Autumn");
        SomeNames.addElement("Melanie");
        SomeNames.addElement("Ariana");
        SomeNames.addElement("Serenity");
        SomeNames.addElement("Stella");
        SomeNames.addElement("Maria");
        SomeNames.addElement("Molly");
        SomeNames.addElement("Caroline");
        SomeNames.addElement("Genesis");
        SomeNames.addElement("Kaitlyn");
        SomeNames.addElement("Eva");
        SomeNames.addElement("Jessica");
        SomeNames.addElement("Angelina");
        SomeNames.addElement("Valeria");
        SomeNames.addElement("Gabrielle");
        SomeNames.addElement("Naomi");
        SomeNames.addElement("Mariah");
        SomeNames.addElement("Natalia");
        SomeNames.addElement("Paige");
        SomeNames.addElement("Rachel");
        SomeNames.addElement("Rachel");
        SomeNames.addElement("Beyonce");
        SomeNames.addElement("Jayla");
        SomeNames.addElement("Ayana");
        SomeNames.addElement("Zari");
        SomeNames.addElement("Laqueta");
        SomeNames.addElement("Aisha");
        SomeNames.addElement("Kimani");
        SomeNames.addElement("Kayla");
        SomeNames.addElement("Shaniqua");
        SomeNames.addElement("Imani");
        SomeNames.addElement("Demarco");
        SomeNames.addElement("Dion");
        SomeNames.addElement("Chikae");
        SomeNames.addElement("Deion");
        SomeNames.addElement("Malik");
        SomeNames.addElement("Darius");
        SomeNames.addElement("Deon");
        SomeNames.addElement("Demond");
        SomeNames.addElement("Elon");
        SomeNames.addElement("Taye");
        SomeNames.addElement("Alexander");
        SomeNames.addElement("Sebastián");
        SomeNames.addElement("Daniel");
        SomeNames.addElement("Ángel");
        SomeNames.addElement("Santiago");
        SomeNames.addElement("Diego");
        SomeNames.addElement("Alejandro");
        SomeNames.addElement("Christopher");
        SomeNames.addElement("David");
        SomeNames.addElement("Anthony");
        SomeNames.addElement("Sophia");
        SomeNames.addElement("Camila");
        SomeNames.addElement("Isabella");
        SomeNames.addElement("Valeria");
        SomeNames.addElement("Mia");
        SomeNames.addElement("Allison");
        SomeNames.addElement("Gabriela");
        SomeNames.addElement("Emily");
        SomeNames.addElement("Ashley");
        SomeNames.addElement("Nicole");


        SomeJobs.addElement("Grocer");
        SomeJobs.addElement("Farmer");
        SomeJobs.addElement("Shopkeeper");
        SomeJobs.addElement("Chef");
        

    }
 public String HisHersFinder(String name) {
        String his_hers = "";
        switch (name) {
            case "Jacob": his_hers = "he";  break;
            case "Ethan": his_hers = "he";  break;
             case "Michael": his_hers = "he";  break;
              case "Jayden": his_hers = "he";  break;
               case "William": his_hers = "he";  break;
                case "Alexander": his_hers = "he";  break;
                 case "Noah": his_hers = "he";  break;
                  case "Daniel": his_hers = "he";  break;
                   case "Aiden": his_hers = "he";  break;
                    case "Anthony": his_hers = "he";  break;
                     case "Joshua": his_hers = "he";  break;
      
        case "Elijah": his_hers = "he";  break;
        case "Logan": his_hers = "he";  break;
        case "Mason": his_hers = "he";  break;
        case "Christopher": his_hers = "he";  break;
        case "David": his_hers = "he";  break;
        case "Andrew": his_hers = "he";  break;
        case "Matthew": his_hers = "he";  break;
       
    case "James": his_hers = "he";  break;
       case "Joseph": his_hers = "he";  break;
       case "Gabriel": his_hers = "he";  break;
       case "Benjamin": his_hers = "he";  break;
       case "Ryan": his_hers = "he";  break;
       case "Samuel": his_hers = "he";  break;
       case "Jackson": his_hers = "he";  break;
       case "John": his_hers = "he";  break;
       case "Nathan": his_hers = "he";  break;
       case "Jonathan": his_hers = "he";  break;
       case "Christian": his_hers = "he";  break;
       case "Liam": his_hers = "he";  break;
       case "Dylan": his_hers = "he";  break;
       case "Landon": his_hers = "he";  break;
       case "Caleb": his_hers = "he";  break;
       case "Tyler": his_hers = "he";  break;
       case "Lucas": his_hers = "he";  break;
       case "Evan": his_hers = "he";  break;
       case "Gavin": his_hers = "he";  break;
       case "Nicholas": his_hers = "he";  break;
       case "Isaac": his_hers = "he";  break;
       case "Brayden": his_hers = "he";  break;
       case "Luke": his_hers = "he";  break;
       case "Angel": his_hers = "he";  break;
       case "Brandon": his_hers = "he";  break;
       case "Jack": his_hers = "he";  break;
       case "Isaiah": his_hers = "he";  break;
       case "Jordan": his_hers = "he";  break;
       case "Owen": his_hers = "he";  break;
       case "Carter": his_hers = "he";  break;
       case "Connor": his_hers = "he";  break;
       case "Justin": his_hers = "he";  break;
       case "Jose": his_hers = "he";  break;
       case "Jeremiah": his_hers = "he";  break;
       case "Julian": his_hers = "he";  break;
       case "Robert": his_hers = "he";  break;
       case "Aaron": his_hers = "he";  break;
       case "Adrian": his_hers = "he";  break;
       case "Wyatt": his_hers = "he";  break;
       case "Kevin": his_hers = "he";  break;
       case "Hunter": his_hers = "he";  break;
       case "Cameron": his_hers = "he";  break;
       case "Zachary": his_hers = "he";  break;
       case "Thomas": his_hers = "he";  break;
       case "Charles": his_hers = "he";  break;
       case "Austin": his_hers = "he";  break;
       case "Eli": his_hers = "he";  break;
       case "Chase": his_hers = "he";  break;
       case "Henry": his_hers = "he";  break;
       case "Sebastian": his_hers = "he";  break;
       case "Jason": his_hers = "he";  break;
       case "Levi": his_hers = "he";  break;
       case "Xavier": his_hers = "he";  break;
       case "Ian": his_hers = "he";  break;
       case "Colton": his_hers = "he";  break;
       case "Dominic": his_hers = "he";  break;
       case "Juan": his_hers = "he";  break;
       case "Cooper": his_hers = "he";  break;
       case "Josiah": his_hers = "he";  break;
       case "Luis": his_hers = "he";  break;
       case "Ayden": his_hers = "he";  break;
       case "Carson": his_hers = "he";  break;
       case "Adam": his_hers = "he";  break;
       case "Nathaniel": his_hers = "he";  break;
       case "Brody": his_hers = "he";  break;
       case "Tristan": his_hers = "he";  break;
       case "Diego": his_hers = "he";  break;
       case "Parker": his_hers = "he";  break;
       case "Blake": his_hers = "he";  break;
       case "Oliver": his_hers = "he";  break;
       case "Cole": his_hers = "he";  break;
       case "Carlos": his_hers = "he";  break;
       case "Jaden": his_hers = "he";  break;
       case "Jesus": his_hers = "he";  break;
       case "Alex": his_hers = "he";  break;
       case "Aidan": his_hers = "he";  break;
       case "Eric": his_hers = "he";  break;
       case "Hayden": his_hers = "he";  break;
       case "Bryan": his_hers = "he";  break;
       case "Max": his_hers = "he";  break;
       case "Jaxon": his_hers = "he";  break;
       case "Brian": his_hers = "he";  break;
       case "Isabella": his_hers = "she";  break;
       case "Sophia": his_hers = "she";  break;
       case "Emma": his_hers = "she";  break;
       case "Olivia": his_hers = "she";  break;
       case "Ava": his_hers = "she";  break;
       case "Emily": his_hers = "she";  break;
       case "Abigail": his_hers = "she";  break;
       case "Madison": his_hers = "she";  break;
       case "Chloe": his_hers = "she";  break;
       case "Mia": his_hers = "she";  break;
       case "Addison": his_hers = "she";  break;
       case "Elizabeth": his_hers = "she";  break;
       case "Ella": his_hers = "she";  break;
       case "Natalie": his_hers = "she";  break;
       case "Samantha": his_hers = "she";  break;
       case "Alexis": his_hers = "she";  break;
       case "Lily": his_hers = "she";  break;
       case "Grace": his_hers = "she";  break;
       case "Hailey": his_hers = "she";  break;
       case "Alyssa": his_hers = "she";  break;
       case "Lillian": his_hers = "she";  break;
       case "Hannah": his_hers = "she";  break;
       case "Avery": his_hers = "she";  break;
       case "Leah": his_hers = "she";  break;
       case "Nevaeh": his_hers = "she";  break;
       case "Sofia": his_hers = "she";  break;
       case "Ashley": his_hers = "she";  break;
       case "Anna": his_hers = "she";  break;
       case "Brianna": his_hers = "she";  break;
       case "Sarah": his_hers = "she";  break;
       case "Zoe": his_hers = "she";  break;
       case "Victoria": his_hers = "she";  break;
       case "Gabriella": his_hers = "she";  break;
       case "Brooklyn": his_hers = "she";  break;
       case "Kaylee": his_hers = "she";  break;
       case "Taylor": his_hers = "she";  break;
       case "Layla": his_hers = "she";  break;
       case "Allison": his_hers = "she";  break;
       case "Evelyn": his_hers = "she";  break;
       case "Riley": his_hers = "she";  break;
       case "Amelia": his_hers = "she";  break;
       case "Khloe": his_hers = "she";  break;
       case "Makayla": his_hers = "she";  break;
       case "Aubrey": his_hers = "she";  break;
       case "Charlotte": his_hers = "she";  break;
       case "Savannah": his_hers = "she";  break;
       case "Zoey": his_hers = "she";  break;
       case "Bella": his_hers = "she";  break;
       case "Kayla": his_hers = "she";  break;
       case "Alexa": his_hers = "she";  break;
       case "Peyton": his_hers = "she";  break;
       case "Audrey": his_hers = "she";  break;
       case "Claire": his_hers = "she";  break;
       case "Arianna": his_hers = "she";  break;
       case "Julia": his_hers = "she";  break;
 case "Aaliyah": his_hers = "she";  break;
       case "Kylie": his_hers = "she";  break;
       case "Lauren": his_hers = "she";  break;
       case "Sophie": his_hers = "she";  break;
       case "Sydney": his_hers = "she";  break;
       case "Camila": his_hers = "she";  break;
       case "Jasmine": his_hers = "she";  break;
       case "Morgan": his_hers = "she";  break;
       case "Alexandra": his_hers = "she";  break;
       case "Jocelyn": his_hers = "she";  break;
       case "Gianna": his_hers = "she";  break;
       case "Maya": his_hers = "she";  break;
       case "Kimberly": his_hers = "she";  break;
       case "Mackenzie": his_hers = "she";  break;
       case "Katherine": his_hers = "she";  break;
       case "Destiny": his_hers = "she";  break;
       case "Brooke": his_hers = "she";  break;
       case "Trinity": his_hers = "she";  break;
       case "Faith": his_hers = "she";  break;
       case "Lucy": his_hers = "she";  break;
       case "Madelyn": his_hers = "she";  break;
       case "Madeline": his_hers = "she";  break;
       case "Bailey": his_hers = "she";  break;
       case "Payton": his_hers = "she";  break;
       case "Andrea": his_hers = "she";  break;
       case "Autumn": his_hers = "she";  break;
       case "Melanie": his_hers = "she";  break;
       case "Ariana": his_hers = "she";  break;
       case "Serenity": his_hers = "she";  break;
       case "Stella": his_hers = "she";  break;
       case "Maria": his_hers = "she";  break;
       case "Molly": his_hers = "she";  break;
       case "Caroline": his_hers = "she";  break;
       case "Genesis": his_hers = "she";  break;
       case "Kaitlyn": his_hers = "she";  break;
       case "Eva": his_hers = "she";  break;
       case "Jessica": his_hers = "she";  break;
       case "Angelina": his_hers = "she";  break;
       case "Valeria": his_hers = "she";  break;
       case "Gabrielle": his_hers = "she";  break;
       case "Naomi": his_hers = "she";  break;
       case "Mariah": his_hers = "she";  break;
       case "Natalia": his_hers = "she";  break;
       case "Paige": his_hers = "she";  break;
       case "Rachel": his_hers = "she";  break;
       case "Beyonce": his_hers = "she";  break;
       case "Jayla": his_hers = "she";  break;
       case "Ayana": his_hers = "she";  break;
       case "Zari": his_hers = "she";  break;
       case "Laqueta": his_hers = "she";  break;
       case "Aisha": his_hers = "she";  break;
       case "Kimani": his_hers = "she";  break;
       case "Shaniqua": his_hers = "she";  break;
       case "Imani": his_hers = "she";  break;
       case "Demarco": his_hers = "he";  break;
       case "Dion": his_hers = "he";  break;
       case "Chikae": his_hers = "he";  break;
       case "Deion": his_hers = "he";  break;
       case "Malik": his_hers = "he";  break;
       case "Darius": his_hers = "he";  break;
       case "Deon": his_hers = "he";  break;
       case "Demond": his_hers = "he";  break;
       case "Elon": his_hers = "he";  break;
       case "Taye": his_hers = "he";  break;
       case "Sebastián": his_hers = "he";  break;
       case "Ángel": his_hers = "he";  break;
       case "Santiago": his_hers = "he";  break;
       case "Alejandro": his_hers = "he";  break;
       case "Nicole": his_hers = "she";  break;

        }


        return his_hers;
    }
    public String GenderFinder(String name) {
        String his_hers = "";
        switch (name) {
            case "Jacob": his_hers = "his";  break;
            case "Ethan": his_hers = "his";  break;
             case "Michael": his_hers = "his";  break;
              case "Jayden": his_hers = "his";  break;
               case "William": his_hers = "his";  break;
                case "Alexander": his_hers = "his";  break;
                 case "Noah": his_hers = "his";  break;
                  case "Daniel": his_hers = "his";  break;
                   case "Aiden": his_hers = "his";  break;
                    case "Anthony": his_hers = "his";  break;
                     case "Joshua": his_hers = "his";  break;
      
        case "Elijah": his_hers = "his";  break;
        case "Logan": his_hers = "his";  break;
        case "Mason": his_hers = "his";  break;
        case "Christopher": his_hers = "his";  break;
        case "David": his_hers = "his";  break;
        case "Andrew": his_hers = "his";  break;
        case "Matthew": his_hers = "his";  break;
       
    case "James": his_hers = "his";  break;
       case "Joseph": his_hers = "his";  break;
       case "Gabriel": his_hers = "his";  break;
       case "Benjamin": his_hers = "his";  break;
       case "Ryan": his_hers = "his";  break;
       case "Samuel": his_hers = "his";  break;
       case "Jackson": his_hers = "his";  break;
       case "John": his_hers = "his";  break;
       case "Nathan": his_hers = "his";  break;
       case "Jonathan": his_hers = "his";  break;
       case "Christian": his_hers = "his";  break;
       case "Liam": his_hers = "his";  break;
       case "Dylan": his_hers = "his";  break;
       case "Landon": his_hers = "his";  break;
       case "Caleb": his_hers = "his";  break;
       case "Tyler": his_hers = "his";  break;
       case "Lucas": his_hers = "his";  break;
       case "Evan": his_hers = "his";  break;
       case "Gavin": his_hers = "his";  break;
       case "Nicholas": his_hers = "his";  break;
       case "Isaac": his_hers = "his";  break;
       case "Brayden": his_hers = "his";  break;
       case "Luke": his_hers = "his";  break;
       case "Angel": his_hers = "his";  break;
       case "Brandon": his_hers = "his";  break;
       case "Jack": his_hers = "his";  break;
       case "Isaiah": his_hers = "his";  break;
       case "Jordan": his_hers = "his";  break;
       case "Owen": his_hers = "his";  break;
       case "Carter": his_hers = "his";  break;
       case "Connor": his_hers = "his";  break;
       case "Justin": his_hers = "his";  break;
       case "Jose": his_hers = "his";  break;
       case "Jeremiah": his_hers = "his";  break;
       case "Julian": his_hers = "his";  break;
       case "Robert": his_hers = "his";  break;
       case "Aaron": his_hers = "his";  break;
       case "Adrian": his_hers = "his";  break;
       case "Wyatt": his_hers = "his";  break;
       case "Kevin": his_hers = "his";  break;
       case "Hunter": his_hers = "his";  break;
       case "Cameron": his_hers = "his";  break;
       case "Zachary": his_hers = "his";  break;
       case "Thomas": his_hers = "his";  break;
       case "Charles": his_hers = "his";  break;
       case "Austin": his_hers = "his";  break;
       case "Eli": his_hers = "his";  break;
       case "Chase": his_hers = "his";  break;
       case "Henry": his_hers = "his";  break;
       case "Sebastian": his_hers = "his";  break;
       case "Jason": his_hers = "his";  break;
       case "Levi": his_hers = "his";  break;
       case "Xavier": his_hers = "his";  break;
       case "Ian": his_hers = "his";  break;
       case "Colton": his_hers = "his";  break;
       case "Dominic": his_hers = "his";  break;
       case "Juan": his_hers = "his";  break;
       case "Cooper": his_hers = "his";  break;
       case "Josiah": his_hers = "his";  break;
       case "Luis": his_hers = "his";  break;
       case "Ayden": his_hers = "his";  break;
       case "Carson": his_hers = "his";  break;
       case "Adam": his_hers = "his";  break;
       case "Nathaniel": his_hers = "his";  break;
       case "Brody": his_hers = "his";  break;
       case "Tristan": his_hers = "his";  break;
       case "Diego": his_hers = "his";  break;
       case "Parker": his_hers = "his";  break;
       case "Blake": his_hers = "his";  break;
       case "Oliver": his_hers = "his";  break;
       case "Cole": his_hers = "his";  break;
       case "Carlos": his_hers = "his";  break;
       case "Jaden": his_hers = "his";  break;
       case "Jesus": his_hers = "his";  break;
       case "Alex": his_hers = "his";  break;
       case "Aidan": his_hers = "his";  break;
       case "Eric": his_hers = "his";  break;
       case "Hayden": his_hers = "his";  break;
       case "Bryan": his_hers = "his";  break;
       case "Max": his_hers = "his";  break;
       case "Jaxon": his_hers = "his";  break;
       case "Brian": his_hers = "his";  break;
       case "Isabella": his_hers = "her";  break;
       case "Sophia": his_hers = "her";  break;
       case "Emma": his_hers = "her";  break;
       case "Olivia": his_hers = "her";  break;
       case "Ava": his_hers = "her";  break;
       case "Emily": his_hers = "her";  break;
       case "Abigail": his_hers = "her";  break;
       case "Madison": his_hers = "her";  break;
       case "Chloe": his_hers = "her";  break;
       case "Mia": his_hers = "her";  break;
       case "Addison": his_hers = "her";  break;
       case "Elizabeth": his_hers = "her";  break;
       case "Ella": his_hers = "her";  break;
       case "Natalie": his_hers = "her";  break;
       case "Samantha": his_hers = "her";  break;
       case "Alexis": his_hers = "her";  break;
       case "Lily": his_hers = "her";  break;
       case "Grace": his_hers = "her";  break;
       case "Hailey": his_hers = "her";  break;
       case "Alyssa": his_hers = "her";  break;
       case "Lillian": his_hers = "her";  break;
       case "Hannah": his_hers = "her";  break;
       case "Avery": his_hers = "her";  break;
       case "Leah": his_hers = "her";  break;
       case "Nevaeh": his_hers = "her";  break;
       case "Sofia": his_hers = "her";  break;
       case "Ashley": his_hers = "her";  break;
       case "Anna": his_hers = "her";  break;
       case "Brianna": his_hers = "her";  break;
       case "Sarah": his_hers = "her";  break;
       case "Zoe": his_hers = "her";  break;
       case "Victoria": his_hers = "her";  break;
       case "Gabriella": his_hers = "her";  break;
       case "Brooklyn": his_hers = "her";  break;
       case "Kaylee": his_hers = "her";  break;
       case "Taylor": his_hers = "her";  break;
       case "Layla": his_hers = "her";  break;
       case "Allison": his_hers = "her";  break;
       case "Evelyn": his_hers = "her";  break;
       case "Riley": his_hers = "her";  break;
       case "Amelia": his_hers = "her";  break;
       case "Khloe": his_hers = "her";  break;
       case "Makayla": his_hers = "her";  break;
       case "Aubrey": his_hers = "her";  break;
       case "Charlotte": his_hers = "her";  break;
       case "Savannah": his_hers = "her";  break;
       case "Zoey": his_hers = "her";  break;
       case "Bella": his_hers = "her";  break;
       case "Kayla": his_hers = "her";  break;
       case "Alexa": his_hers = "her";  break;
       case "Peyton": his_hers = "her";  break;
       case "Audrey": his_hers = "her";  break;
       case "Claire": his_hers = "her";  break;
       case "Arianna": his_hers = "her";  break;
       case "Julia": his_hers = "her";  break;
 case "Aaliyah": his_hers = "her";  break;
       case "Kylie": his_hers = "her";  break;
       case "Lauren": his_hers = "her";  break;
       case "Sophie": his_hers = "her";  break;
       case "Sydney": his_hers = "her";  break;
       case "Camila": his_hers = "her";  break;
       case "Jasmine": his_hers = "her";  break;
       case "Morgan": his_hers = "her";  break;
       case "Alexandra": his_hers = "her";  break;
       case "Jocelyn": his_hers = "her";  break;
       case "Gianna": his_hers = "her";  break;
       case "Maya": his_hers = "her";  break;
       case "Kimberly": his_hers = "her";  break;
       case "Mackenzie": his_hers = "her";  break;
       case "Katherine": his_hers = "her";  break;
       case "Destiny": his_hers = "her";  break;
       case "Brooke": his_hers = "her";  break;
       case "Trinity": his_hers = "her";  break;
       case "Faith": his_hers = "her";  break;
       case "Lucy": his_hers = "her";  break;
       case "Madelyn": his_hers = "her";  break;
       case "Madeline": his_hers = "her";  break;
       case "Bailey": his_hers = "her";  break;
       case "Payton": his_hers = "her";  break;
       case "Andrea": his_hers = "her";  break;
       case "Autumn": his_hers = "her";  break;
       case "Melanie": his_hers = "her";  break;
       case "Ariana": his_hers = "her";  break;
       case "Serenity": his_hers = "her";  break;
       case "Stella": his_hers = "her";  break;
       case "Maria": his_hers = "her";  break;
       case "Molly": his_hers = "her";  break;
       case "Caroline": his_hers = "her";  break;
       case "Genesis": his_hers = "her";  break;
       case "Kaitlyn": his_hers = "her";  break;
       case "Eva": his_hers = "her";  break;
       case "Jessica": his_hers = "her";  break;
       case "Angelina": his_hers = "her";  break;
       case "Valeria": his_hers = "her";  break;
       case "Gabrielle": his_hers = "her";  break;
       case "Naomi": his_hers = "her";  break;
       case "Mariah": his_hers = "her";  break;
       case "Natalia": his_hers = "her";  break;
       case "Paige": his_hers = "her";  break;
       case "Rachel": his_hers = "her";  break;
       case "Beyonce": his_hers = "her";  break;
       case "Jayla": his_hers = "her";  break;
       case "Ayana": his_hers = "her";  break;
       case "Zari": his_hers = "her";  break;
       case "Laqueta": his_hers = "her";  break;
       case "Aisha": his_hers = "her";  break;
       case "Kimani": his_hers = "her";  break;
       case "Shaniqua": his_hers = "her";  break;
       case "Imani": his_hers = "her";  break;
       case "Demarco": his_hers = "his";  break;
       case "Dion": his_hers = "his";  break;
       case "Chikae": his_hers = "his";  break;
       case "Deion": his_hers = "his";  break;
       case "Malik": his_hers = "his";  break;
       case "Darius": his_hers = "his";  break;
       case "Deon": his_hers = "his";  break;
       case "Demond": his_hers = "his";  break;
       case "Elon": his_hers = "his";  break;
       case "Taye": his_hers = "his";  break;
       case "Sebastián": his_hers = "his";  break;
       case "Ángel": his_hers = "his";  break;
       case "Santiago": his_hers = "his";  break;
       case "Alejandro": his_hers = "his";  break;
       case "Nicole": his_hers = "her";  break;

        }


        return his_hers;
    }
}
